favioavila88/ecaptiva

package.json, src/components/Styles/organisms/accordion/Accordion.css, src/components/Styles/organisms/carrousel/Carrousel.css, src/components/Styles/pages/carrers/CarrersRow_5.css, src/components/Styles/pages/home/HomeRow_1.css, src/components/Styles/pages/home/HomeRow_4.css, src/components/Styles/pages/home/HomeRow_9.css, src/components/organisms/accordion/Accordion.jsx, src/components/organisms/accordion/Collapse.jsx, src/components/organisms/carrousel/Carrousel.jsx, src/components/organisms/carrousel/CarrouselCard.jsx, src/components/organisms/home/HomeRow_1.jsx, src/components/organisms/home/HomeRow_2.jsx, src/components/organisms/home/HomeRow_5.jsx, src/components/organisms/home/HomeRow_9.jsx, src/components/organisms/services/ServicesRow_5.jsx, src/constants/TechStacks.jsx
This PR contains the implementation to add the accordion functionality
=> Add implementation to add accordion

README.md
This PR contains fix to:
Bug 16: Actualizar la descripcion del 'Readme' del respositorio 'ecaptiva'
=> Updating description on README file

src/components/organisms/carrers/CarrersRow_1.jsx
This PR contains a fix to:
Bug 13: El texto 'BECOME A TRUEPER!' debe modificarse
=> Updating text on CAREERS tab

src/components/Styles/pages/carrers/CarrersRow_2.css, src/components/Styles/pages/home/HomeRow_3.css, src/components/organisms/carrers/CareerBase.jsx, src/components/organisms/company/CompanyRow_4.jsx
Contains fix to:
Bug 14: Modificar texto de tab "COMPANY"
=> Updating code to modify text in Company tab

src/components/organisms/contactUs/ContactUsRow_3.jsx
This PR contains:
Bug 12: Eliminar el texto 'CONTACT US'
=> Removing unnecessary text

src/components/Styles/pages/theProof/TheProofRow_3.css, src/components/organisms/theProof/TheProofRow_3.jsx
This PR contains:
Bug 4: Eliminar las opciones 'ALL', 'BANNERS CAMPAIGN', 'ECOMMERCE', 'INTERACTIVE KIOSK', 'MOBILE APP', 'WEB APP', 'WEB SITE'  del header de la pagina
=> Removing options in the THE PROOF section

src/components/Styles/pages/theProof/TheProofRow_3.css, src/components/organisms/theProof/TheProofRow_3.jsx
Contains fix to:
Bug 6: Los banners de la pestaña 'THE PROOF' no muestran el mismo espacio en el body de la página
=> Adding implementation to align items on THE PROOF section

index.html
This PR contains fix to:
Bug 15: Al iniciar la pagina 'Captiva' el titulo del tab del browser muestra 'Vite + React'
=> Updating title

src/components/Styles/pages/theProof/TheProofRow_3.css, src/components/organisms/theProof/TheProofRow_3.jsx
This PR contains fix to:
Bug 7:  The banners titles are lost when banner background is white
=> Adding validation to change color in the text

src/components/Styles/molecules/contactUs/Formulary.css
This PR contains fix for the Bug21:
El tamaño del boton 'Send' es muy grande
=> Updating code to resize button in Contact form

src/components/Styles/molecules/footer/LogosWorkColumn.css, src/components/Styles/molecules/footer/ReferenceDateColumn.css, src/components/Styles/organisms/footer/Footer.css, src/components/organisms/footer/Footer.jsx, src/components/organisms/getAnEstimate/GetAnEstimateRow_2.jsx
This PR contains fix for the BUG 20:
La seccion 'BRANDS THAT TRUST US' no tiene un contenedor para los logos
=> Adding styles to align footer

src/components/organisms/home/HomeRow_4.jsx, src/constants/BrandsTrustUs.jsx
Bug18:
La seccion 'BRANDS THAT TRUST US' no tiene un contenedor para los logos
=> Adding container

src/components/Styles/molecules/header/Navbar.css, src/components/molecules/header/Navbar.jsx, src/constants/MenuList.jsx
Improvement 3:
Agregar el tab 'Captiva Academy'
=> Adding code to add CAPTIVA ACADEMY option

src/components/organisms/services/ServicesRow_4.jsx
Improvement 1:
El botón 'Contact Us' no redirige al formulario 'Contáctenos'
=> Adding code to go to GET AN ESTIMATE

src/components/Styles/pages/carrers/CarrersRow_5.css, src/components/organisms/carrers/CarrersRow_5.jsx
Improvement2:
El botón APPLY HERE' no redirige a la pestaña 'GET AN ESTIMATE'
=> Updating code to APPLY HERE button

src/components/Styles/molecules/footer/NavBarColumn.css, src/components/Styles/molecules/header/Navbar.css, src/components/molecules/footer/NavBarColumn.jsx
This PR contains the fix to bug22:
Las opciones del menu 'SITEMAP' no se resaltan cuando estamos en el mismo tab del navegador
=> Updating styles to add  highlight to sitemap

src/components/Styles/pages/home/HomeRow_8.css, src/components/organisms/home/HomeRow_8.jsx
This PR contains the fix for the bug 23:
El texto  y iconos de 'Golbal','Different Industries', 'Best talents', Remote Firts' y 'Worldwidw projects  no estan alineados
=> Updating styles to align content

src/components/organisms/carrousel/CarrouselCard.jsx
This PR contains fix to:
Bug 26: 
En la seccion de 'What Our Clients Say' al hacer mouse over en el icono no se muestra el cursor
=> Updating styles to show cursor

src/components/molecules/footer/NavBarColumn.jsx, src/constants/MenuList.jsx, src/router/Router.jsx
This PR contains changes for:
Improvement 5:
Deshabilitar el tab THE PROOF' con su contenido y agregar el tab 'BLOG'
=> Updating code to hide The Proof tab and add BLOG

src/components/Styles/organisms/footer/Footer.css, src/components/Styles/organisms/header/Header.css, src/components/Styles/pages/home/HomeRow_11.css, src/components/Styles/pages/home/HomeRow_4.css, src/components/Styles/pages/home/HomeRow_8.css, src/components/Styles/pages/home/HomeRow_9.css, src/components/Styles/pages/services/ServicesRow_5.css, src/components/organisms/home/HomeRow_7.jsx
Reverts favioavila88/ecaptiva#47
=> Revert "Updating styles to responsive rows"

index.html, src/components/Styles/pages/home/HomeRow_3.css, src/components/Styles/pages/home/HomeRow_4.css, src/components/Styles/pages/home/HomeRow_5.css, src/components/Styles/pages/home/HomeRow_9.css, src/components/organisms/carrousel/CarrouselCard.jsx, src/components/organisms/home/HomeRow_4.jsx, src/components/organisms/home/HomeRow_5.jsx
Adding styles to have responsive view on android mobiles:
=> Adding styles to responsive view
